services:
  iris:
    build:
      context: .
      args:
        - IMAGE=${IMAGE_IRIS_EM}
    # image: ${IMAGE_IRIS_EM} # EXTENDED MAINTENANCE
    init: true
    container_name: iris-zen
    hostname: iris-zen
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - type: bind
      source: ./volumes
      target: /volumes
    - type: bind
      source: ./key
      target: /key
    - type: bind
      source: ./code
      target: /code
    - type: bind
      source: ./data
      target: /data
    command: --key /key/iris.key -a /code/configure_default_password.sh
    # command: --key key/iris.key -a /code/configure_change_password.sh
    ports:
      - 31004:1972
    environment:
      - ISC_DATA_DIRECTORY=/volumes/${EXTENDED_MAINTENANCE}

  webgateway:
    image: ${WEBGATEWAY}
    init: true
    hostname: ${WEBGATEWAY_NAME}
    ports:
    - ${WEBGATEWAY_PORT_HTTP}:80
    - ${WEBGATEWAY_PORT_HTTPS}:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway